### PR TITLE
ADS fixes

### LINKED ISSUE #532: [BUG] Regression: Document shortcuts don't work when switching tabs
CTRL+W should close a document. However, when switching between documents, it often doesn't work (for example closing multiple documents one after the other with the shortcut).

It only starts working after you once click into the document itself (not the tab at the top).

@Sanakan8472 I assume this is a side-effect of the shortcut change in #516

### PR DESCRIPTION
**Pull request by Sanakan8472**
* Closing a document will set the keyboard focus to the new window that is on top of the dock area (fixes #532).
* Restored ads::CDockManager::ConfigFlags which were changed to being static with some update.
* Enabled FocusHighlighting in ADS and tweaked the css style.
* Fixed compile error due to precision loss.

### CODE REVIEW

File: Code/Engine/GameEngine/Effects/Shake/Implementation/CameraShakeComponent.cpp [hunk 1]
```diff
@@ -67,7 +67,7 @@ void ezCameraShakeComponent::GenerateKeyframe()
 
   if (deviation > ezAngle())
   {
-    m_Rotation += ezAngle::Radian(pWorld->GetRandomNumberGenerator().DoubleMinMax(ezAngle::Degree(120).GetRadian(), ezAngle::Degree(240).GetRadian()));
```
Comment (jankrassnigg) [inline Code/Engine/GameEngine/Effects/Shake/Implementation/CameraShakeComponent.cpp]: I just relocated this file in my PR, so I have integrated your fix there. In case my PR goes in first, you can just remove this change from your PR.

**Review by jankrassnigg — APPROVED** [review]

File: Code/Engine/GameEngine/Effects/Shake/Implementation/CameraShakeComponent.cpp (hunk 1 above)
Comment (Sanakan8472) [reply Code/Engine/GameEngine/Effects/Shake/Implementation/CameraShakeComponent.cpp]: Ok, I'll removed this change then.
