### PR TITLE
Fixed cross platform serialization issues with visual scripts

### LINKED ISSUE #1404: [BUG] Visual Scripts don't work on 32 bit systems
Data can't be loaded, due to alignment differences.

### PR DESCRIPTION
**Pull request by C-Core**
Visual scripts had a couple of things pre-compiled that depend on the target platform like byteoffsets for local variables etc. These offsets could differ e.g. from a 64bit to 32bit platform.
Now only platform independent data is serialized and and things like byteoffsets for local variables are calculated at load time.

### CODE REVIEW

File: Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScript_inl.h [hunk 1]
```diff
@@ -87,6 +87,24 @@ EZ_ALWAYS_INLINE ezVisualScriptGraphDescription::DataOffset ezVisualScriptGraphD
...
+{
+  return m_NumOutputDataOffsets <= EZ_ARRAY_SIZE(m_OutputDataOffsets.m_Embedded) ? m_OutputDataOffsets.m_Embedded : m_OutputDataOffsets.m_Ptr;
+}
+
+// static
+template <typename T>
+EZ_ALWAYS_INLINE constexpr ezUInt32 ezVisualScriptGraphDescription::Node::GetUserDataAlignment()
+{
+  // Ensures at least 8 byte alignment, thus making it compatible between 32 and 64 bit platforms.
+  return ezMath::Max<ezUInt32>(EZ_ALIGNMENT_OF(T), 8u);
```
Comment (jankrassnigg) [inline Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScript_inl.h]: I never understood why EZ_ALIGNMENT_OF works the way it does. Is this really the correct choice here? Because IIRC it also uses some MAX value internally.

**Review by jankrassnigg — APPROVED** [review]

File: Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScript_inl.h (hunk 1 above)
Comment (C-Core) [reply Code/EnginePlugins/VisualScriptPlugin/Runtime/VisualScript_inl.h]: Looks like we don't need the EZ_ALIGNMENT_OF macro anymore, at least it in msvc as far as I tested it. Let's see what CI and the other platforms say.
