### PR TITLE
Fixed crash when recreating decal atlas after profile change

### LINKED ISSUE #1868: [BUG] engine crashes in Asset Profiles dialog (Testing Chambers)
**Bug description:**
engine crashes in Asset Profiles dialog (Testing Chambers)

**How to Reproduce:**
1. open Testing Chambers - Main scene
2. go to menu: Project -> Project Settings -> Asset Profiles...
3. Just press OK
4. engine crashed

```py
ezCrashHandler_WriteMiniDump: No dump-file location specified.
***Unhandled Exception:***
Exception: c0000005
***Stack Trace:***
C:\git\ezEngine\Code\Engine\RendererCore\Decals\Implementation\DecalManager.cpp(441):'ezDecalManager::MarkRuntimeDecalAsUsed'
C:\git\ezEngine\Code\Engine\RendererCore\Lights\Implementation\SpotLightComponent.cpp(252):'ezSpotLightComponent::OnMsgExtractRenderData'
C:\git\ezEngine\Code\Engine\Foundation\Reflection\Implementation\RTTI.cpp(375):'ezRTTI::DispatchMessage'
C:\git\ezEngine\Code\Engine\Core\World\Implementation\Component.cpp(257):'ezComponent::SendMessageInternal'
C:\git\ezEngine\Code\Engine\RendererCore\Pipeline\Implementation\Extractor.cpp(218):'ezExtractor::ExtractRenderData'
C:\git\ezEngine\Code\Engine\RendererCore\Pipeline\Implementation\Extractor.cpp(312):'ezVisibleObjectsExtractor::Extract'
C:\git\ezEngine\Code\Engine\RendererCore\Pipeline\Implementation\RenderPipeline.cpp(950):'ezRenderPipeline::ExtractData'
C:\git\ezEngine\Code\Engine\RendererCore\Pipeline\Implementation\View.cpp(161):'ezView::ExtractData'
C:\git\ezEngine\Code\Engine\Foundation\Threading\Implementation\Task.cpp(55):'ezTask::Run'
C:\git\ezEngine\Code\Engine\Foundation\Threading\Implementation\TaskSystemTasks.cpp(141):'ezTaskSystem::ExecuteTask'
C:\git\ezEngine\Code\Engine\Foundation\Threading\Implementation\TaskSystemTasks.cpp(225):'ezTaskSystem::HelpExecutingTasks'
C:\git\ezEngine\Code\Engine\Foundation\Threading\Implementation\TaskSystemGroups.cpp(285):'ezTaskSystem::WaitForGroup'
C:\git\ezEngine\Code\Engine\RendererCore\RenderWorld\Implementation\RenderWorld.cpp(489):'ezRenderWorld::ExtractMainViews'
C:\git\ezEngine\Code\Engine\GameEngine\GameApplication\Implementation\GameApplication.cpp(338):'ezGameApplication::UpdateWorldsAndExtractViews'
C:\git\ezEngine\Code\Engine\Foundation\Threading\Implementation\Task.cpp(55):'ezTask::Run'
C:\git\ezEngine\Code\Engine\Foundation\Threading\Implementation\TaskSystemTasks.cpp(141):'ezTaskSystem::ExecuteTask'
Shutting down Engine Process
```

### PR DESCRIPTION
**Pull request by C-Core**
* When the platform profile changed the runtime decal manager was completely destroyed which resulted in a crash when trying to access internal data the next frame. Now only the atlas is destroyed and recreated which should fix this issue. Fixes #1868 
* Also cleaned up curve sampling in expressions

### CODE REVIEW

File: Code/EnginePlugins/ProcGenPlugin/Tasks/Implementation/Utils.cpp [hunk 1]
```diff
@@ -126,94 +126,20 @@ namespace
...
 ezExpressionFunction ezProcGenExpressionFunctions::s_ApplyVolumesFunc = {
-  {ezMakeHashedString("ApplyVolumes"), ezExpression::FunctionDesc::TypeList(s_ApplyVolumesTypes), 5, ezExpression::RegisterType::Float},
+  {ezMakeHashedString("applyVolumes"), ezExpression::FunctionDesc::TypeList(s_ApplyVolumesTypes), 5, ezExpression::RegisterType::Float},
   &ApplyVolumes,
   &ApplyVolumesValidate,
 };
 
 ezExpressionFunction ezProcGenExpressionFunctions::s_GetInstanceSeedFunc = {
-  {ezMakeHashedString("GetInstanceSeed"), ezExpression::FunctionDesc::TypeList(), 0, ezExpression::RegisterType::Int},
+  {ezMakeHashedString("getInstanceSeed"), ezExpression::FunctionDesc::TypeList(), 0, ezExpression::RegisterType::Int},
```
Comment (jankrassnigg) [inline Code/EnginePlugins/ProcGenPlugin/Tasks/Implementation/Utils.cpp:138]: Since you rename all the functions, is this the style that we should use here? I also used it in my change, but it's not really the ez style. Maybe we should change it the other way round?

Comment (C-Core) [reply Code/EnginePlugins/ProcGenPlugin/Tasks/Implementation/Utils.cpp:138]: I changed it to that because all the builtin functions use this style as well (coming from hlsl)
