### PR TITLE
Sprite and shape icon fixes

### LINKED ISSUE #440: [BUG] Sprite rendering issue - Sprite disappears in some cases
**Bug description:**
The sprite component does not render in the "Play the game" mode when using an orthographic camera.

**How to Reproduce:**
While running in the editor, the sprite will disappear from the ortho graphic camera preview.
If you click on a perspective camera that is looking at the sprite as well then click on the ortho camera again in the hierarchy then the sprite will show up in the ortho camera preview again.

**Screenshots:**
Before play/simulate:
image

After play/simulate:
image

**Dev-branch commit hash:**
0e7e50c1fa3d9a0fff6a9f41496e076ef383954a

### PR DESCRIPTION
**Pull request by C-Core**
* Allow sprites in orthographic views
* Don't show shape icons for inactive components
* Don't show skybox in texture preview

### CODE REVIEW

**Review by jankrassnigg — APPROVED** [review]

File: Code/Editor/EditorFramework/Assets/SimpleAssetDocument.h [hunk 1]
```diff
@@ -108,16 +108,22 @@ class ezSimpleAssetDocument : public BaseClass
     : BaseClass(szDocumentPath, EZ_DEFAULT_NEW(ezSimpleDocumentObjectManager<PropertyType>), engineConnectionType)
     , m_LightSettings(bEnableDefaultLighting)
   {
-    ezEditorPreferencesUser* pPreferences = ezPreferences::QueryPreferences<ezEditorPreferencesUser>();
-    pPreferences->ApplyDefaultValues(m_LightSettings);
+    if (bEnableDefaultLighting)
```
Comment (C-Core) [inline Code/Editor/EditorFramework/Assets/SimpleAssetDocument.h:111]: @Sanakan8472 if bEnableDefaultLighting was false the lighting was still enabled via the default settings, so I added this check here. I guess that was your intention with the bEnableDefaultLighting bool?

Comment (Sanakan8472) [reply Code/Editor/EditorFramework/Assets/SimpleAssetDocument.h:111]: Yes that was wrong. It probably only worked as long as I didn't have the editor preferences fully implemented.

**Review by Sanakan8472 — APPROVED** [review]
