### PR TITLE
Visual script and proc gen fixes, light shafts tint color

### LINKED ISSUE #1888: [BUG] Monster Attack sample is crashing the engine
**Bug description:**

Monster Attack sample is crashing the engine:

```js
    *** Assertion ***: File: "C:\git\ezEngine\Code\EnginePlugins\VisualScriptPlugin\Runtime\VisualScriptData.cpp", Line: "412", Function: "ezVisualScriptDataStorage::GetDataAsVariant", Expression: "", Message: "Not implemented"
    C:\git\ezEngine\Code\Editor\EditorEngineProcess\EngineProcGameApp.cpp(132):'ezEngineProcessGameApplication::EditorAssertHandler'
    C:\git\ezEngine\Code\EnginePlugins\InspectorPlugin\InspectorApp.cpp(34):'TelemetryAssertHandler'
    C:\git\ezEngine\Code\EnginePlugins\VisualScriptPlugin\Runtime\VisualScriptData.cpp(566):'ezVisualScriptDataStorage::GetDataAsVariant'
    C:\git\ezEngine\Code\EnginePlugins\VisualScriptPlugin\Runtime\VisualScriptNodeFunctions.cpp(127):'`anonymous namespace'::NodeFunction_ReflectedFunction'
    C:\git\ezEngine\Code\EnginePlugins\VisualScriptPlugin\Runtime\VisualScript.cpp(378):'ezVisualScriptExecutionContext::Execute'
    C:\git\ezEngine\Code\EnginePlugins\VisualScriptPlugin\Runtime\VisualScriptFunctionProperty.cpp(25):'ezVisualScriptFunctionProperty::Execute'
    C:\git\ezEngine\Code\Engine\GameEngine\StateMachine\Implementation\StateMachineState_Script.cpp(103):'`anonymous namespace'::ScriptInstanceData::CallOnEnter'
    C:\git\ezEngine\Code\Engine\GameEngine\StateMachine\Implementation\StateMachineState_Script.cpp(60):'`anonymous namespace'::ScriptInstanceData::InstantiateScript'
    C:\git\ezEngine\Code\Engine\GameEngine\StateMachine\Implementation\StateMachineState_Script.cpp(163):'ezStateMachineState_Script::OnEnter'
    C:\git\ezEngine\Code\Engine\GameEngine\StateMachine\Implementation\StateMachine.cpp(486):'ezStateMachineInstance::EnterCurrentState'
    C:\git\ezEngine\Code\Engine\GameEngine\StateMachine\Implementation\StateMachine.cpp(478):'ezStateMachineInstance::SetStateInternal'
    C:\git\ezEngine\Code\Engine\GameEngine\StateMachine\Implementation\StateMachine.cpp(396):'ezStateMachineInstance::SetState'
    C:\git\ezEngine\Code\Engine\GameEngine\StateMachine\Implementation\StateMachine.cpp(416):'ezStateMachineInstance::Update'
    C:\git\ezEngine\Code\Engine\GameEngine\StateMachine\Implementation\StateMachineComponent.cpp(207):'ezStateMachineComponentManager::Update'
    C:\git\ezEngine\Code\Engine\Core\World\Implementation\World.cpp(1106):'ezWorld::UpdateSynchronous'
    C:\git\ezEngine\Code\Engine\Core\World\Implementation\World.cpp(526):'ezWorld::Update'
    C:\git\ezEngine\Code\Engine\Core\World\Implementation\World.cpp(1090):'ezWorld::UpdateFromThread'
    C:\git\ezEngine\Code\Engine\Foundation\Threading\Implementation\Task.cpp(55):'ezTask::Run'
    C:\git\ezEngine\Code\Engine\Foundation\Threading\Implementation\TaskSystemTasks.cpp(141):'ezTaskSystem::ExecuteTask'
    C:\git\ezEngine\Code\Engine\Foundation\Threading\Implementation\TaskSystemTasks.cpp(225):'ezTaskSystem::HelpExecutingTasks'
    C:\git\ezEngine\Code\Engine\Foundation\Threading\Implementation\TaskSystemGroups.cpp(285):'ezTaskSystem::WaitForGroup'
    C:\git\ezEngine\Code\Engine\GameEngine\GameApplication\Implementation\GameApplication.cpp(318):'ezGameApplication::UpdateWorldsAndExtractViews'
    C:\git\ezEngine\Code\Engine\Foundation\Threading\Implementation\Task.cpp(55):'ezTask::Run'
    C:\git\ezEngine\Code\Engine\Foundation\Threading\Implementation\TaskSystemTasks.cpp(141):'ezTaskSystem::ExecuteTask'
    C:\git\ezEngine\Code\Engine\Foundation\Threading\Implementation\TaskWorkerThread.cpp(99):'ezTaskWorkerThread::Run'
    *** Assertion ***      Expression: ""     Function: "ezVisualScriptDataStorage::GetDataAsVariant"     File: "C:\git\ezEngine\Code\EnginePlugins\VisualScriptPlugin\Runtime\VisualScriptData.cpp"     Line: 412     Message: "Not implemented"
```

**How to Reproduce:**
1. Open Monster Attack sample and launch the game.

**Dev-branch commit hash:**
af52e6834a24d25264899cd176e06d3d80eb4644

### LINKED ISSUE #1894: [BUG] Two trees are placed on the same spot (procedural placement)
**Bug description:**
Two trees are placed on the same spot (procedural placement)

**How to Reproduce:**
1. open Testing Chambers, Vegetation scene.
2. disable "Player Start Point: SpotBot" to enable fly camera
3. disable LowPolyVegetation, but enable HighPolyVegetation.
4. open ThickForest asset from HighPolyVegetation object and change Placement Mode to Fixed, so it is easy to see a doubling of trees. Save asset.
5. return to scene and press Play The Game (important)
6. if You look at bottom of some trees, You will find that they are doubled.

**Screenshots:**

Image

"Dev" build.

### PR DESCRIPTION
**Pull request by C-Core**
* Fixed visual script GetDataAsVariant. Fixes #1888
* Proc placement: don't add new tiles multiple times when visible from multiple views. Fixes #1894
* Light shafts tint color

### CODE REVIEW

File: Data/Base/Shaders/Pipeline/LightShaftsConstants.h [hunk 1]
```diff
@@ -5,6 +5,8 @@
 
 CONSTANT_BUFFER2(ezLightShaftsConstants, 3, BG_RENDER_PASS)
 {
+  COLOR4F(LightShaftsTintColor);
```
Comment (jankrassnigg) [inline Data/Base/Shaders/Pipeline/LightShaftsConstants.h:8]: You use a float4 color here, but the component uses a Color gamma. Why not use an ezColor there as well?

Comment (C-Core) [reply Data/Base/Shaders/Pipeline/LightShaftsConstants.h:8]: There is no need for an HDR color, we already have an intensity property
