### PR TITLE
Moved State Machine Asset transform to engine process

### LINKED ISSUE #1200: [BUG] StateMachineStates can't be added through game plugins
If you try to use a StateMachineState that is defined in a game plugin, the editor tries to create an instance of it, to serialize the data. This doesn't work, because the code is not loaded into the editor.

A different solution has to be used for the state serialization.

### PR DESCRIPTION
**Pull request by C-Core**
* The connection information is now stored in the connection object itself instead of in metadata. 
* This allowed removal of all special handling for the render pipeline transform.
* Moved state machine asset transform to engine process so it can instantiate states from custom plugins. Fixes #1200 
* Re-saved all assets to reflect recent format changes.

### CODE REVIEW

File: Code/EditorPlugins/Assets/EditorPluginAssets/StateMachineAsset/StateMachineGraph.cpp [hunk 1]
```diff
@@ -175,13 +124,28 @@ const ezRTTI* ezStateMachineNodeManager::GetConnectionType() const
...
+  if (pCommandHistory == nullptr)
+    return;
+
+  if (e.m_EventType == ezDocumentObjectStructureEvent::Type::AfterObjectAdded)
   {
-    if (m_pInitialStateObject == nullptr && IsAnyState(e.m_pObject) == false)
+    if (GetInitialState() == nullptr && IsAnyState(e.m_pObject) == false)
     {
-      SetInitialState(e.m_pObject);
+      if (pCommandHistory->IsInTransaction() && e.m_pObject->GetTypeAccessor().GetValue(s_szIsInitialState) == false)
```
Comment (Sanakan8472) [inline Code/EditorPlugins/Assets/EditorPluginAssets/StateMachineAsset/StateMachineGraph.cpp]: Nit: As `GetInitialState()` will itterate over all root nodes, it might make sense to test `pCommandHistory->IsInTransaction()` before that to skip the function call in the general case.

File: Code/Tools/Libs/ToolsFoundation/NodeObject/Implementation/DocumentNodeManager.cpp [hunk 2]
```diff
@@ -427,67 +436,90 @@ void ezDocumentNodeManager::RestoreMetaDataAfterLoading(const ezAbstractObjectGr
...
       {
-        ezLog::Error("Unknown input pin '{}' on '{}'. The connection has been removed.", connectionMetaData.m_TargetPin, pTarget->GetType()->GetTypeName());
         RemoveObject(pObject);
         DestroyObject(pObject);
-        continue;
       }
+    }
+    else
+    {
+      DocumentNodeManager_ConnectionMetaData connectionMetaData;
```
Comment (Sanakan8472) [inline Code/Tools/Libs/ToolsFoundation/NodeObject/Implementation/DocumentNodeManager.cpp:500]: When is this case called? If it's not a node and not a connection, is it a sub-object or a legacy connection? What will happen to sub-object in this function anyways?

File: Code/EditorPlugins/Assets/EnginePluginAssets/StateMachineAsset/StateMachineContext.cpp [hunk 3]
```diff
@@ -0,0 +1,139 @@
...
+  auto AddState = [&](const ezStateMachineNode* pNode, const ezUuid& uuid)
+  {
+    const ezString& name = pNode->m_sName;
+    if (stateNames.Contains(name))
+    {
+      return ezStatus(ezFmt("A state named '{}' already exists. State names have to be unique.", name));
+    }
+    stateNames.Insert(name);
+
+    ezUniquePtr<ezStateMachineState> pState = ezUniquePtr<ezStateMachineState>(pNode->m_pType, nullptr);
```
Comment (Sanakan8472) [inline Code/EditorPlugins/Assets/EnginePluginAssets/StateMachineAsset/StateMachineContext.cpp:63]: Is this effectively creating an `ezUniquePtr` without ownership?

**Review by Sanakan8472 — APPROVED** [review]

File: Code/Tools/Libs/ToolsFoundation/NodeObject/Implementation/DocumentNodeManager.cpp (hunk 2 above)
Comment (C-Core) [reply Code/Tools/Libs/ToolsFoundation/NodeObject/Implementation/DocumentNodeManager.cpp:500]: I introduced a new class for connections so the IsConnection check above won't work. In this case we read the metadata and create a new object of the new class and set the properties from metadata. 
A sub-object is not a node, nor a connection nor will it have a valid DocumentNodeManager_ConnectionMetaData, so nothing happens in this case.

File: Code/EditorPlugins/Assets/EnginePluginAssets/StateMachineAsset/StateMachineContext.cpp (hunk 3 above)
Comment (C-Core) [reply Code/EditorPlugins/Assets/EnginePluginAssets/StateMachineAsset/StateMachineContext.cpp:63]: Yes, in this case the unique ptr acts like a raw pointer. I'm not super happy with this workaround but the state machine desc needs a unique ptr, which makes sense for the runtime usecase. So either I would need a different desc just for the export code or I would need to clone the state machine state/transition objects here just to get an unique ptr to them.

File: Code/EditorPlugins/Assets/EditorPluginAssets/StateMachineAsset/StateMachineGraph.cpp (hunk 1 above)
Comment (C-Core) [reply Code/EditorPlugins/Assets/EditorPluginAssets/StateMachineAsset/StateMachineGraph.cpp]: Done
