### PR TITLE
Fixes and improvements for the C++ workflow

### LINKED ISSUE #817: [BUG] Editor sometimes removes plugin references
If you load the sample game project without having the DLL compiled, the editor removes the plugin reference from the ddl file.
This may also happen to other things under certain circumstances.
This should not happen.

### PR DESCRIPTION
**Pull request by jankrassnigg**
* Fixed #817: Project specific plugin bundles don't need to be copied to the Bin folder anymore. This prevents plugin references getting lost when switching between build types.
* When building the C++ code, the CMake solution is now automatically regenerated when the build type differs (Debug, Dev, Shipping).
* The editor warns now that the build may fail, when a debugger is attached.

### CODE REVIEW

File: Code/Engine/Foundation/IO/FileSystem/DeferredFileWriter.h [hunk 1]
```diff
@@ -22,7 +22,7 @@ class EZ_FOUNDATION_DLL ezDeferredFileWriter : public ezStreamWriter
 
   /// \brief Upon calling this the content is written to the file specified with SetOutput().
   /// The return value is EZ_FAILURE if the file could not be opened or not completely written.
-  ezResult Close(); // [tested]
+  ezResult Close(bool* out_bWasWrittenTo = nullptr); // [tested]
```
Comment (C-Core) [inline Code/Engine/Foundation/IO/FileSystem/DeferredFileWriter.h:25]: Isn't out_bWasWrittenTo the same as the returned ezResult?

Comment (jankrassnigg) [reply Code/Engine/Foundation/IO/FileSystem/DeferredFileWriter.h:25]: No, if the content is identical, the result will be true, but written to will be false.
